added my name to contributers
zero-to-mastery/Keiko-Corp pull request #196
Opened 2020-10-02 13:00 UTC by UnderDaHood

# Pull Request Template

> Please provide all of the details below. Pull requests missing any of the information below will be closed!

**Summarise what this PR fixes:** < enter details >

**Fixes #:** < Enter Issue ID/URL >

# Checklist:
(Add an `x` between the brackets to check the items)

- [ ] I have summarised what this PR fixes above
- [ ] I have provided the issue ID/URL above
- [ ] This PR fixes only the issue mentioned above (create separate PRs for separate issues)
- [ ] I was the first one to claim the issue or I created the issue

2020-10-02 16:47 UTC, abdus requested changes

2020-10-02 16:47 UTC, abdus commented on assets/css/nav-styles.css
> +  height: 200px;
don't set height. let the content take whatever height it requires. if it's really necessary, use `max-height` instead

2020-10-02 16:47 UTC, abdus commented on assets/css/nav-styles.css
> +  height: 1vh;
remove this

2020-10-03 17:05 UTC, MattCSmith commented
Closing this PR due to the age and conflicts. Feel free to resolve and reopen 🙂

2020-10-03 17:05 UTC, closed without merging