fixes #4 : Feature one
zero-to-mastery/Keiko-Corp pull request #63
Opened 2020-10-01 17:59 UTC by Udaygajavalli

Added feature one with free vector and demo text

2020-10-01 18:14 UTC, abdus requested changes

2020-10-01 18:14 UTC, abdus commented on style.css
> +=======
remove this please

2020-10-01 18:14 UTC, abdus commented on style.css
> +>>>>>>> e65f4b6f4140c89b380f7785c962d31bfa6c1f8a
remove this

2020-10-01 18:23 UTC, abdus approved these changes

2020-10-01 18:24 UTC, abdus commented
resolve conflicts, please.

2020-10-02 03:02 UTC, Udaygajavalli commented
It seems everything is fine but again branch conflict.

2020-10-02 03:27 UTC, brittneypostma commented
This no longer shows conflicts, I'm going to pull it in. It does not align with the pdf style wise though and will need to be adjusted in another issue. I have added the assets for the projects section to the images folder now.

2020-10-02 03:28 UTC, merged